-- ML_Icon_Colorer_DefaultColors
-- Author: yiboy
-- DateCreated: 9/29/2024 11:05:29 AM
--------------------------------------------------------------

firaxis_default_colors = {
	{
		ColorType = "COLOR_BLACK",
		Name = "LOC_COLOR_BLACK_NAME",
		R = 0,
		G = 0,
		B = 0,
		A = 255,
	},
	--{
		--ColorType = "COLOR_WHITE",
		--Name = "LOC_COLOR_WHITE_NAME",
		--R = 255,
		--G = 255,
		--B = 255,
		--A = 255,
	--},
	--{
		--ColorType = "COLOR_BLUE",
		--Name = "LOC_COLOR_BLUE_NAME",
		--R = 0,
		--G = 0,
		--B = 255,
		--A = 255,
	--},
	--{
		--ColorType = "COLOR_RED",
		--Name = "LOC_COLOR_RED_NAME",
		--R = 255,
		--G = 0,
		--B = 0,
		--A = 255,
	--},
	--{
		--ColorType = "COLOR_GREEN",
		--Name = "LOC_COLOR_GREEN_NAME",
		--R = 0,
		--G = 255,
		--B = 0,
		--A = 255,
	--},
	--ºì+ÂÌ=»Æ
	--ºì+À¶=Ñóºì
	--ÂÌ+À¶=Çà
	--{
		--ColorType = "COLOR_YELLOW",
		--Name = "LOC_COLOR_GREEN_NAME",
		--R = 255,
		--G = 255,
		--B = 0,
		--A = 255,
	--},


	--{
		--ColorType = "COLOR_PLAYER_BARBARIAN_PRIMARY",	--Ò°ÂùÈË-ºì
		--Name = "LOC_COLOR_PLAYER_BARBARIAN_PRIMARY_NAME",
		--R = 191,
		--G = 0,
		--B = 0,
		--A = 255,
	--},
	----×¢Òâ£¬Ò°ÂùÈËºÚÊÇ´¿ºÚ
	--{
		--ColorType = "COLOR_PLAYER_AMERICA_PRIMARY",	--ÃÀ¹ú-ÉîÀ¶
		--Name = "LOC_COLOR_PLAYER_AMERICA_PRIMARY_NAME",
		--R = 32,
		--G = 57,
		--B = 124,
		--A = 255,
	--},
	----ÃÀ¹ú°×ÊÇ´¿°×
	--{
		--ColorType = "COLOR_PLAYER_BRAZIL_PRIMARY",	--°ÍÎ÷-ÂÌ
		--Name = "LOC_COLOR_PLAYER_BRAZIL_PRIMARY_NAME",
		--R = 23,
		--G = 163,
		--B = 68,
		--A = 255,
	--},
	--{
		--ColorType = "COLOR_PLAYER_BRAZIL_SECONDARY",	--°ÍÎ÷-»Æ
		--Name = "LOC_COLOR_PLAYER_BRAZIL_SECONDARY_NAME",
		--R = 225,
		--G = 211,
		--B = 32,
		--A = 255,
	--},
	--{
		--ColorType = "COLOR_PLAYER_CHINA_PRIMARY",	--ÖÐ¹ú-ÂÌ
		--Name = "LOC_COLOR_PLAYER_CHINA_PRIMARY_NAME",
		--R = 125,
		--G = 150,
		--B = 60,
		--A = 255,
	--},
	----ÖÐ¹ú°×ÊÇ´¿°×


	{
		ColorType = "COLOR_STANDARD_RED_LT",
		Name = "LOC_COLOR_STANDARD_RED_LT_NAME",
		R = 229,
		G = 117,
		B = 116,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_RED_MD",
		Name = "LOC_COLOR_STANDARD_RED_MD_NAME",
		R = 202,
		G = 20,
		B = 21,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_RED_DK",
		Name = "LOC_COLOR_STANDARD_RED_DK_NAME",
		R = 120,
		G = 0,
		B = 1,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_ORANGE_LT",
		Name = "LOC_COLOR_STANDARD_ORANGE_LT_NAME",
		R = 255,
		G = 178,
		B = 60,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_ORANGE_MD",
		Name = "LOC_COLOR_STANDARD_ORANGE_MD_NAME",
		R = 255,
		G = 129,
		B = 18,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_ORANGE_DK",
		Name = "LOC_COLOR_STANDARD_ORANGE_DK_NAME",
		R = 120,
		G = 61,
		B = 2,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_YELLOW_LT",
		Name = "LOC_COLOR_STANDARD_YELLOW_LT_NAME",
		R = 234,
		G = 225,
		B = 157,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_YELLOW_MD",
		Name = "LOC_COLOR_STANDARD_YELLOW_MD_NAME",
		R = 247,
		G = 216,
		B = 1,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_YELLOW_DK",
		Name = "LOC_COLOR_STANDARD_YELLOW_DK_NAME",
		R = 134,
		G = 114,
		B = 2,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_GREEN_LT",
		Name = "LOC_COLOR_STANDARD_GREEN_LT_NAME",
		R = 121,
		G = 224,
		B = 119,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_GREEN_MD",
		Name = "LOC_COLOR_STANDARD_GREEN_MD_NAME",
		R = 97,
		G = 191,
		B = 34,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_GREEN_DK",
		Name = "LOC_COLOR_STANDARD_GREEN_DK_NAME",
		R = 21,
		G = 108,
		B = 48,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_AQUA_LT",
		Name = "LOC_COLOR_STANDARD_AQUA_LT_NAME",
		R = 125,
		G = 236,
		B = 227,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_AQUA_MD",
		Name = "LOC_COLOR_STANDARD_AQUA_MD_NAME",
		R = 0,
		G = 192,
		B = 155,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_AQUA_DK",
		Name = "LOC_COLOR_STANDARD_AQUA_DK_NAME",
		R = 1,
		G = 79,
		B = 81,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_BLUE_LT",
		Name = "LOC_COLOR_STANDARD_BLUE_LT_NAME",
		R = 116,
		G = 163,
		B = 243,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_BLUE_MD",
		Name = "LOC_COLOR_STANDARD_BLUE_MD_NAME",
		R = 0,
		G = 79,
		B = 206,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_BLUE_DK",
		Name = "LOC_COLOR_STANDARD_BLUE_DK_NAME",
		R = 1,
		G = 42,
		B = 108,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_PURPLE_LT",
		Name = "LOC_COLOR_STANDARD_PURPLE_LT_NAME",
		R = 183,
		G = 128,
		B = 230,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_PURPLE_MD",
		Name = "LOC_COLOR_STANDARD_PURPLE_MD_NAME",
		R = 109,
		G = 0,
		B = 205,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_PURPLE_DK",
		Name = "LOC_COLOR_STANDARD_PURPLE_DK_NAME",
		R = 55,
		G = 0,
		B = 101,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_MAGENTA_LT",
		Name = "LOC_COLOR_STANDARD_MAGENTA_LT_NAME",
		R = 255,
		G = 153,
		B = 255,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_MAGENTA_MD",
		Name = "LOC_COLOR_STANDARD_MAGENTA_MD_NAME",
		R = 255,
		G = 0,
		B = 255,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_MAGENTA_DK",
		Name = "LOC_COLOR_STANDARD_MAGENTA_DK_NAME",
		R = 117,
		G = 0,
		B = 115,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_WHITE_LT",
		Name = "LOC_COLOR_STANDARD_WHITE_LT_NAME",
		R = 249,
		G = 249,
		B = 249,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_WHITE_MD",
		Name = "LOC_COLOR_STANDARD_WHITE_MD_NAME",
		R = 83,
		G = 83,
		B = 83,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_WHITE_MD2",
		Name = "LOC_COLOR_STANDARD_WHITE_MD2_NAME",
		R = 174,
		G = 174,
		B = 174,
		A = 255,
	},
	{
		ColorType = "COLOR_STANDARD_WHITE_DK",
		Name = "LOC_COLOR_STANDARD_WHITE_DK_NAME",
		R = 24,
		G = 24,
		B = 24,
		A = 255,
	},
	
}

