INSERT INTO	PlayerColors
		(Type,										Usage,			PrimaryColor,							SecondaryColor)
VALUES	
-- Trade
		('CIVILIZATION_PHANTA_CS_TK_GUIYANG',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_LINGLING',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_CHANGSHA',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_WULING',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_JINCHENG',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_FUHAN',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_HENEI',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_CHENLIU',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_YIZHOU',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_JINHAN',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_JINGNAN',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_DONGYE',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_TRADE_SECONDARY'),

-- Religious
		('CIVILIZATION_PHANTA_CS_TK_BAIBO',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_RUNAN',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_TAISHAN',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_HEISHAN',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_KUAIJI',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_CANGWU',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_YAMATAI',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_BYEONHAN',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_QIANG',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_DI',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_OKJEO',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_QINGZHOU',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_RELIGIOUS_SECONDARY'),
		
-- Militaristic
		('CIVILIZATION_PHANTA_CS_TK_WANCHENG',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_JIANGXIA',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_XIANBEI',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_SOUTHERN_XIONGNU',	'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_LIAOXI_WUHUAN',		'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_SHANYUE',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_WU',				'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_CHEN',				'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_GOGURYEO',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_MAHAN',				'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_CHIYANG',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_MEI',				'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_KUNAKOKU',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY'),
		('CIVILIZATION_PHANTA_CS_TK_WUXIMAN',			'Minor',		'COLOR_PLAYER_CITY_STATE_PRIMARY',		'COLOR_PLAYER_CITY_STATE_MILITARISTIC_SECONDARY');
