-- TKH_Icons
-- Author: PurpleSoul
-- DateCreated: 5/24/2025 10:24:56 PM
--------------------------------------------------------------
CREATE TABLE IF NOT EXISTS TKH_ArmouryProjects ( 
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL, 
    Tags TEXT NOT NULL, 
    Cost INTEGER NOT NULL
);


INSERT INTO TKH_ArmouryProjects(Name, Cost, Tags) 
VALUES 
('LIUDANPAO', 2, 'CLASS_SIEGE_TKH_UNIT'),
('RANSHAODAN', 2, 'CLASS_SIEGE_TKH_UNIT'),
('ZHUANJIAZU', 2, 'CLASS_SIEGE_TKH_UNIT'),
('PIJIA', 2, 'CLASS_MELEE_TKH_UNIT,CLASS_ANTI_CAVALRY_TKH_UNIT'),
('LIANJIA', 2, 'CLASS_MELEE_TKH_UNIT,CLASS_ANTI_CAVALRY_TKH_UNIT'),
('YILIAOBAO', 3, 'CLASS_TKH_UNIT'),
('ZHONGBANJIA', 1, 'CLASS_HEAVY_CAVALRY_TKH_UNIT,CLASS_HEAVY_CHARIOT_TKH_UNIT,CLASS_LIGHT_CAVALRY_TKH_UNIT,CLASS_LIGHT_CHARIOT_TKH_UNIT'),
('QISHIDUN', 1, 'CLASS_HEAVY_CAVALRY_TKH_UNIT,CLASS_HEAVY_CHARIOT_TKH_UNIT,CLASS_LIGHT_CAVALRY_TKH_UNIT,CLASS_LIGHT_CHARIOT_TKH_UNIT'),
('QISHIJIAN', 2, 'CLASS_HEAVY_CAVALRY_TKH_UNIT,CLASS_HEAVY_CHARIOT_TKH_UNIT,CLASS_LIGHT_CAVALRY_TKH_UNIT,CLASS_LIGHT_CHARIOT_TKH_UNIT'),
('GANGJIANTOU', 2, 'CLASS_RANGED_TKH_UNIT'),
('DUJIANTOU', 2, 'CLASS_RANGED_TKH_UNIT'),
('WUSHU', 2, 'CLASS_RANGED_TKH_UNIT'),
('SHENFA', 3, 'CLASS_RANGED_TKH_UNIT'),
('CHANGQIANGZHEN', 2, 'CLASS_ANTI_CAVALRY_TKH_UNIT'),
('GOULIANQIANG', 3, 'CLASS_ANTI_CAVALRY_TKH_UNIT'),
('GUIJIAZHEN', 2, 'CLASS_MELEE_TKH_UNIT'),
('GANGJIAN', 2, 'CLASS_MELEE_TKH_UNIT'),
('JUNXUE', 5, 'CLASS_MELEE_TKH_UNIT,CLASS_ANTI_CAVALRY_TKH_UNIT'),
('TONGXUE', 5, 'CLASS_RANGED_TKH_UNIT'),
('BAIJIAXING', 3, 'CLASS_TKH_UNIT'),
('SANZIJING', 3, 'CLASS_TKH_UNIT'),
('SUNZIBINGFASHANG', 2, 'CLASS_TKH_UNIT'),
('SUNZIBINGFAXIA', 2, 'CLASS_TKH_UNIT'),
('CHANGMAOZHEN', 2, 'CLASS_ANTI_CAVALRY_TKH_UNIT'),
('JIANDUNZHEN', 2, 'CLASS_MELEE_TKH_UNIT'),
('QIBINGZHEN', 2, 'CLASS_HEAVY_CAVALRY_TKH_UNIT,CLASS_HEAVY_CHARIOT_TKH_UNIT,CLASS_LIGHT_CAVALRY_TKH_UNIT,CLASS_LIGHT_CHARIOT_TKH_UNIT'),
('JIANYUZHEN', 2, 'CLASS_RANGED_TKH_UNIT');


INSERT INTO IconDefinitions(Name, Atlas, [Index])
SELECT 'ICON_PROJECT_TKH_EA_'||Name, 'ICON_ATLAS_PROJECTS', 11
FROM TKH_ArmouryProjects;