-- =========================
-- SYSTEM
-- =========================

MELEE_COMBAT = 748940753
RANGED_COMBAT = 784649805

TKH_ObjectType = {}
TKH_ObjectType.Game = -1
TKH_ObjectType.Player = 0
TKH_ObjectType.Unit = 1
TKH_ObjectType.City = 2
TKH_ObjectType.Plot = 3

EXTRA_ACTION_TYPE = {}
EXTRA_ACTION_TYPE.MAX = 1
EXTRA_ACTION_TYPE.TEMP = 2

TXT_CONFIRM_POPUP_YES = Locale.Lookup("LOC_CONFIRM_PROMPT_YES")
TXT_CONFIRM_POPUP_NO = Locale.Lookup("LOC_CONFIRM_PROMPT_NO")
DELETE_CITY_EXCHANGE = 1000



CombatVSComponentTypes = {}
CombatVSComponentTypes.UNIT_UNIT = 1
CombatVSComponentTypes.UNIT_CITY = 2
CombatVSComponentTypes.UNIT_DISTRICT = 4
CombatVSComponentTypes.CITY_UNIT = 8
CombatVSComponentTypes.DISTRICT_UNIT = 16

-- 单位击杀叠加最大攻击力
MELEES_UTNI_COMBAT_STRENGTH_BY_PER_KILL_MAX = 10
-- 特殊兵种击杀叠加最大攻击力
SPECIAL_UNIT_COMBAT_STRENGTH_BY_PER_KILL_MAX = 5
-- 副将击杀叠加最大攻击力
SECONDARY_HERO_COMBAT_STRENGTH_PER_KILL_MAX = 10
-- =========================
-- PROJECT
-- =========================
CREATE_EQUIPMENT_GOLD_AMOUNT = 1000
CREATE_EQUIPMENT_HORSES_AMOUNT = 120
CREATE_EQUIPMENT_IRON_AMOUNT = 120

-- CREATE_EQUIPMENT_GOLD_AMOUNT = 1
-- CREATE_EQUIPMENT_HORSES_AMOUNT = 1
-- CREATE_EQUIPMENT_IRON_AMOUNT = 1

PROJECT_CREATE_EQUIPMENT_MOUNT = 'PROJECT_CREATE_EQUIPMENT_MOUNT'
PROJECT_CREATE_EQUIPMENT_MOUNT_INDEX = GameInfo.Projects[PROJECT_CREATE_EQUIPMENT_MOUNT].Index
PROJECT_CREATE_EQUIPMENT_WEAPON = 'PROJECT_CREATE_EQUIPMENT_WEAPON'
PROJECT_CREATE_EQUIPMENT_WEAPON_INDEX = GameInfo.Projects[PROJECT_CREATE_EQUIPMENT_WEAPON].Index

-- =========================
-- CIVIC
-- =========================

CIVIC_FEUDALISM_INDEX = GameInfo.Civics['CIVIC_FEUDALISM'].Index

-- =========================
-- RESOURCE
-- =========================

RESOURCE_HORSES_INDEX = GameInfo.Resources['RESOURCE_HORSES'].Index
RESOURCE_IRON_INDEX = GameInfo.Resources['RESOURCE_IRON'].Index

GREAT_CITIES_RESOURCE = {}
GREAT_CITIES_RESOURCE['咸阳'] = { RESOURCE_IRON_INDEX, 4 }
GREAT_CITIES_RESOURCE['长安'] = { RESOURCE_IRON_INDEX, 4 }

GREAT_CITIES_RESOURCE['雒阳'] = { RESOURCE_IRON_INDEX, 4 }
GREAT_CITIES_RESOURCE['洛阳'] = { RESOURCE_IRON_INDEX, 4 }

GREAT_CITIES_RESOURCE['成都'] = { RESOURCE_IRON_INDEX, 4 }

GREAT_CITIES_RESOURCE['许'] = { RESOURCE_IRON_INDEX, 10 }
GREAT_CITIES_RESOURCE['许昌'] = { RESOURCE_IRON_INDEX, 10 }

GREAT_CITIES_RESOURCE['临淄'] = { RESOURCE_IRON_INDEX, 8 }
GREAT_CITIES_RESOURCE['邺城'] = { RESOURCE_IRON_INDEX, 8 }

GREAT_CITIES_RESOURCE['纪郢'] = { RESOURCE_HORSES_INDEX, 6 }
GREAT_CITIES_RESOURCE['江陵'] = { RESOURCE_HORSES_INDEX, 6 }

GREAT_CITIES_RESOURCE['单于庭'] = { RESOURCE_IRON_INDEX, 3 }

GREAT_CITIES_RESOURCE['绛'] = { RESOURCE_IRON_INDEX, 3 }
GREAT_CITIES_RESOURCE['晋阳'] = { RESOURCE_IRON_INDEX, 3 }

GREAT_CITIES_RESOURCE['蓟'] = { RESOURCE_IRON_INDEX, 3 }
GREAT_CITIES_RESOURCE['广阳'] = { RESOURCE_IRON_INDEX, 3 }
GREAT_CITIES_RESOURCE['北京'] = { RESOURCE_IRON_INDEX, 3 }

GREAT_CITIES_RESOURCE['会稽'] = { RESOURCE_IRON_INDEX, 3 }

GREAT_CITIES_RESOURCE['江州'] = { RESOURCE_HORSES_INDEX, 3 }
GREAT_CITIES_RESOURCE['襄阳'] = { RESOURCE_HORSES_INDEX, 3 }
GREAT_CITIES_RESOURCE['建宁'] = { RESOURCE_HORSES_INDEX, 5 }
GREAT_CITIES_RESOURCE['豫章'] = { RESOURCE_HORSES_INDEX, 3 }
GREAT_CITIES_RESOURCE['江夏'] = { RESOURCE_HORSES_INDEX, 3 }
GREAT_CITIES_RESOURCE['长沙'] = { RESOURCE_HORSES_INDEX, 3 }
GREAT_CITIES_RESOURCE['汉中'] = { RESOURCE_HORSES_INDEX, 3 }
GREAT_CITIES_RESOURCE['夷洲'] = { RESOURCE_HORSES_INDEX, 3 }
GREAT_CITIES_RESOURCE['寿春'] = { RESOURCE_IRON_INDEX, 3 }
GREAT_CITIES_RESOURCE['武威'] = { RESOURCE_HORSES_INDEX, 6 }
GREAT_CITIES_RESOURCE['代郡'] = { RESOURCE_HORSES_INDEX, 4 }
GREAT_CITIES_RESOURCE['汝南'] = { RESOURCE_IRON_INDEX, 3 }


GREAT_CITIES_ENCAMPMENT_COUNT = {}
GREAT_CITIES_ENCAMPMENT_COUNT['咸阳'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['长安'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['雒阳'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['洛阳'] = 4

GREAT_CITIES_ENCAMPMENT_COUNT['成都'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['许'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['许昌'] = 3

GREAT_CITIES_ENCAMPMENT_COUNT['徐'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['建业'] = 3

GREAT_CITIES_ENCAMPMENT_COUNT['临淄'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['邺城'] = 3

GREAT_CITIES_ENCAMPMENT_COUNT['纪郢'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['江陵'] = 3

GREAT_CITIES_ENCAMPMENT_COUNT['睢阳'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['单于庭'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['绛'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['晋阳'] = 2

GREAT_CITIES_ENCAMPMENT_COUNT['邯郸'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['雍'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['陈仓'] = 4

GREAT_CITIES_ENCAMPMENT_COUNT['蓟'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['广阳'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['北京'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['会稽'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['阖闾'] = 3

GREAT_CITIES_ENCAMPMENT_COUNT['襄阳'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['江州'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['建宁'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['南海'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['豫章'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['江夏'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['长沙'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['汉中'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['夷洲'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['寿春'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['武威'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['北地'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['代郡'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['居延'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['下邳'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['辽东'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['乐浪'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['邪马台'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['汝南'] = 4

-- =========================
-- HERO
-- =========================

Ability_CHANGE_UnitTypeUnitCommandArguments = {
    -- ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_SUMMON_LV_LINGQI = {'UNITCOMMAND_CREATE_UNIT', 'Count', '+', 4}
}

S_HERO_SUMMON = {
    ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_SUMMON_LV_BU = 'UNIT_HERO_TKH_GAO_SHUN',
    ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_SUMMON_ZHANG_FEI = 'UNIT_HERO_TKH_ZHANG_XING_CAI',
    ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_SUMMON_MA_CHAO = 'UNIT_HERO_TKH_MA_YUN_LU',
    ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_SUMMON_GUAN_YU = 'UNIT_HERO_TKH_GUAN_YIN_PING',
    ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_SUMMON_ZHAO_YUN = 'UNIT_HERO_TKH_ZHAO_TONG',
}

S_HERO_SUMMON_CITY = {}
S_HERO_SUMMON_CITY['邺城'] = 'UNIT_HERO_TKH_ZHANG_HE'
S_HERO_SUMMON_CITY['朝歌'] = 'UNIT_HERO_TKH_ZHANG_HE'

S_HERO_SUMMON_CITY['许'] = 'UNIT_HERO_TKH_XIA_HOU_DUN'
S_HERO_SUMMON_CITY['许昌'] = 'UNIT_HERO_TKH_XIA_HOU_DUN'

S_HERO_SUMMON_CITY['武威'] = 'UNIT_HERO_TKH_PANG_DE'
S_HERO_SUMMON_CITY['粟特'] = 'UNIT_HERO_TKH_PANG_DE'

S_HERO_SUMMON_CITY['安邑'] = 'UNIT_HERO_TKH_XU_HUANG'

S_HERO_SUMMON_CITY['会稽'] = 'UNIT_HERO_TKH_GAN_NING'

S_HERO_SUMMON_CITY['鄂'] = 'UNIT_HERO_TKH_WEI_YAN'
S_HERO_SUMMON_CITY['长沙'] = 'UNIT_HERO_TKH_WEI_YAN'

S_HERO_SUMMON_CITY['寿春'] = 'UNIT_HERO_TKH_JI_LING'
S_HERO_SUMMON_CITY['舒'] = 'UNIT_HERO_TKH_JI_LING'
S_HERO_SUMMON_CITY['交趾'] = 'UNIT_HERO_TKH_SHI_BIAN'

S_HERO_SUMMON_CITY['成都'] = 'UNIT_HERO_TKH_LIU_YAN'

S_HERO_SUMMON_CITY['易京'] = 'UNIT_HERO_TKH_GONG_SUN_ZAN'
S_HERO_SUMMON_CITY['蓟'] = 'UNIT_HERO_TKH_GONG_SUN_ZAN'

S_HERO_SUMMON_CITY['荆州'] = 'UNIT_HERO_TKH_WEN_PIN'
S_HERO_SUMMON_CITY['江陵'] = 'UNIT_HERO_TKH_WEN_PIN'

S_HERO_SUMMON_CITY['建宁'] = 'UNIT_HERO_TKH_WU_HUO_DONG_ZHU'
S_HERO_SUMMON_CITY['邛都'] = 'UNIT_HERO_TKH_WU_HUO_DONG_ZHU'

S_HERO_SUMMON_CITY['单于庭'] = 'UNIT_HERO_TKH_CHE_LI_JI'

S_HERO_SUMMON_CITY['邪马台'] = 'UNIT_HERO_TKH_BEI_MI_HU'
S_HERO_SUMMON_CITY['海西女真'] = 'UNIT_HERO_TKH_BEI_MI_HU'

S_HERO_SUMMON_CITY['洛阳'] = 'UNIT_HERO_TKH_HUA_XIONG'
S_HERO_SUMMON_CITY['雒阳'] = 'UNIT_HERO_TKH_HUA_XIONG'

S_HERO_SUMMON_CITY['咸阳'] = { 'UNIT_HERO_TKH_LI_JUE', 'UNIT_HERO_TKH_GUO_SI' }
S_HERO_SUMMON_CITY['长安'] = { 'UNIT_HERO_TKH_LI_JUE', 'UNIT_HERO_TKH_GUO_SI' }


-- =========================
-- COMBAT DAMAGE HERO CONSTANTS
-- =========================

DODGE_ABILITIES = {
    -- 赵云
    ABILITY_UNIT_HERO_TKH_ZHAO_YUN = 40,
    ABILITY_TKH_EQUIPMENT_SUIT_YINSHI4 = 15,
    -- 飒露紫
    ABILITY_TKH_EQUIPMENT_SaLuZi = 50,
    -- 张郃副将技能2：受到攻击时有概率闪避伤害
    ABILITY_TKH_S_HERO_SKILL_ZHANG_HE_2 = 35,
}

DECREASE_DAMAGE_ABILITIES = {
    -- 周泰
    ABILITY_UNIT_HERO_TKH_ZHOU_TAI = 0.5,
    -- 甘宁
    ABILITY_TKH_S_HERO_SKILL_GAN_NING_2 = 0.3,
    -- 闪避套装4件效果
    ABILITY_TKH_EQUIPMENT_SUIT_SHANBI4 = 0.15,
    -- 陨铁战甲
    ABILITY_TKH_EQUIPMENT_YunTieZhanJia = 0.05,
    -- 黑铁驹
    ABILITY_TKH_EQUIPMENT_HeiTieJu = 0.05,
    -- 玄铁盾
    ABILITY_TKH_EQUIPMENT_XuanTieDun = 0.05,
}

-- 增加伤害倍率类技能
-- ability = { 几率, 倍率 }
INCREASE_DAMAGE_ABILITIES = {
    ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_UNIQUE_SUN_SHANGXIANG = { 0.5, 1.5 },
    ABILITY_UNIT_HERO_TKH_XU_CHU = { 1, 1, 3 }
}

-- 吸血类技能
LIFE_STEAL_ABILITIES = {
    -- 贪狼
    ABILITY_TKH_SPECIAL_UNIT_TAN_LANG = 0.1,
    -- 高顺3
    ABILITY_TKH_S_HERO_SKILL_GAO_SHUN_3 = 0.1,
    -- 大将军文丑赋予技能
    ABILITY_TKH_GREATPEOPLE_WEN_CHOU = 0.3,
    -- 饮血刀
    ABILITY_TKH_EQUIPMENT_YinXueDao = 0.15,
    ABILITY_TKH_EQUIPMENT_YinXueZhanJia = 0.1,
    ABILITY_TKH_EQUIPMENT_YinXueJu = 0.1,
    ABILITY_TKH_EQUIPMENT_SUIT_YINXUE4 = 0.15,
}


HeroConstants = {}
-- 每次击杀获得的技能点
HeroConstants.SKILL_POINT_PER_KILL = 2
HeroConstants.ZHU_RONG_DAMAGE = 30
HeroConstants.SHA_MOKE_DAMAGE = 10
-- 燕云卫击杀回复生命值/护甲值
HeroConstants.YAN_YUN_GUARD_KILL_HEAL = 80

-- =========================
-- UNIT
-- =========================
-- 特种兵时代加力
UnitEraStrength = { 0, 0, 8, 14, 16, 20, 24, 30, 36 }
-- UnitEraStrength = { 0, 16, 24, 30, 42, 48, 56, 62, 70 }

-- 相邻单位加成
ADJACENT_UNIT =
{
    {
        ABILITY = 'ABILITY_TKH_EA_CHANGMAOZHEN',
        KEY = 'ADJACENT_CLASS_ANTI_CAVALRY',
        BOUNS = 4,
        TAGS = 'CLASS_ANTI_CAVALRY'
    },
    {
        ABILITY = 'ABILITY_TKH_EA_JIANDUNZHEN',
        KEY = 'ADJACENT_CLASS_MELEE',
        BOUNS = 3,
        TAGS = 'CLASS_MELEE'
    },
    {
        ABILITY = 'ABILITY_TKH_EA_JIANYUZHEN',
        KEY = 'ADJACENT_CLASS_RANGED',
        BOUNS = 2,
        TAGS = 'CLASS_RANGED'
    },
    {
        ABILITY = 'ABILITY_TKH_EA_QIBINGZHEN',
        KEY = 'ADJACENT_CLASS_CAVALRY',
        BOUNS = 3,
        TAGS = { 'CLASS_HEAVY_CAVALRY', 'CLASS_LIGHT_CAVALRY', 'CLASS_HEAVY_CHARIOT', 'CLASS_LIGHT_CHARIOT' }
    },
    {
        ABILITY = 'ABILITY_MOD_ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_UNIQUE_MENG_HUO',
        KEY = 'ADJACENT_CLASS_UNIT_HERO_TKH_MENG_HUO_GUARD',
        BOUNS = 4,
        TAGS = { 'CLASS_UNIT_HERO_TKH_MENG_HUO_GUARD' }
    }
}

FULL_PROMOTED_REWARD_ABILITIES = {
    'ABILITY_TKH_FULL_PROMOTED_STRENGTH',
    'ABILITY_TKH_FULL_PROMOTED_DEFEND_STRENGTH',
    'ABILITY_TKH_FULL_PROMOTED_ATTACK_STRENGTH',
    'ABILITY_TKH_FULL_PROMOTED_MOVEMENT_1',
    'ABILITY_TKH_FULL_PROMOTED_MOVEMENT_2',
    'ABILITY_TKH_FULL_PROMOTED_EXTRA_ATTACK',
    'ABILITY_TKH_FULL_PROMOTED_BONUS_SIGHT',
    'ABILITY_TKH_FULL_PROMOTED_SILENT_RUNNING',
    'ABILITY_TKH_FULL_PROMOTED_DOUBLE_ENVELOPMENT',
    -- 特殊兵种独特能力
    'ABILITY_TKH_SPECIAL_UNIT_WU_SHENG_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_YAN_YUN_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_TAN_LANG_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_MENG_HUO_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_ZHANG_LIAO_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_SUN_CE_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_LONG_WEI_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_SHEN_WEI_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_YING_WEI_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_CAO_SHI_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_MAN_ZU_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_HE_SHUO_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_BAI_ER_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_LIN_JIANG_FULL_PROMOTED',
    'ABILITY_TKH_SPECIAL_UNIT_YU_LONG_FULL_PROMOTED',
    -- 副将特殊能力
    'ABILITY_TKH_S_HERO_SKILL_FULL_PROMOTED',
}

FULL_PROMOTED_ABILITY_PARAMETERS = {
    WU_SHENG_RATE = 0.3,
    WU_SHENG_PROBABILITY = 0.5,
}

NOT_FULL_PROMOTED_CLASS_TIMES = 5

NOT_FULL_PROMOTED_CLASS = {
    'CLASS_MELEE_TKH_UNIT',
    'CLASS_ANTI_CAVALRY_TKH_UNIT',
    'CLASS_LIGHT_CAVALRY_TKH_UNIT',
    'CLASS_HEAVY_CAVALRY_TKH_UNIT',
    'CLASS_RECON_TKH_UNIT',
    'CLASS_WARRIOR_MONK_TKH_UNIT',
    'CLASS_UNIT_HERO_TKH_MENG_HUO_GUARD',
    'CLASS_UNIT_HERO_TKH_ZHANG_LIAO_GUARD',
    'CLASS_UNIT_HERO_TKH_SUN_CE_GUARD',
    'CLASS_UNIT_HERO_TKH_LONG_WEI_GUARD',
    'CLASS_UNIT_HERO_TKH_SHEN_WEI_GUARD',
    'CLASS_UNIT_HERO_TKH_WU_SHENG_GUARD',
    'CLASS_UNIT_HERO_TKH_YAN_YUN_GUARD',
    'CLASS_UNIT_HERO_TKH_TAN_LANG_GUARD',
    'CLASS_UNIT_HERO_TKH_CAO_SHI_GUARD',
    'CLASS_UNIT_HERO_TKH_MAN_ZU_GUARD',
    -- 'CLASS_UNIT_HERO_TKH_HE_SHUO_GUARD',
    -- 'CLASS_UNIT_HERO_TKH_BAI_ER_GUARD',

}

FULL_PROMOTED_REWARD = {
    CLASS_MELEE_TKH_UNIT = { EXTRA_ARMOR = 300, EXTRA_HEAL_TURNEND = 30 },
    CLASS_RANGED_TKH_UNIT = { EXTRA_ARMOR = 100 },
    CLASS_ANTI_CAVALRY_TKH_UNIT = { EXTRA_ARMOR = 200, EXTRA_CRIT_PERCENT = 50 },
    CLASS_HEAVY_CAVALRY_TKH_UNIT = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 20 },
    CLASS_LIGHT_CAVALRY_TKH_UNIT = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 20 },
    CLASS_RECON_TKH_UNIT = { EXTRA_ARMOR = 200, EXTRA_CRIT_PERCENT = 50 },
    CLASS_SIEGE_TKH_UNIT = { EXTRA_ARMOR = 100 },
    CLASS_WARRIOR_MONK = { EXTRA_ARMOR = 200, EXTRA_DAMAGE_BOUNS = { 40, 1.5 } },
    CLASS_UNIT_HERO_TKH_MENG_HUO_GUARD = { EXTRA_ARMOR = 250, EXTRA_HEAL_TURNEND = 20 },
    CLASS_UNIT_HERO_TKH_ZHANG_LIAO_GUARD = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 10 },
    CLASS_UNIT_HERO_TKH_SUN_CE_GUARD = { EXTRA_ARMOR = 200, EXTRA_CRIT_PERCENT = 50 },
    CLASS_UNIT_HERO_TKH_LONG_WEI_GUARD = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 10, EXTRA_CRIT_PERCENT = 25, EXTRA_DOOGE = 25 },
    CLASS_UNIT_HERO_TKH_SHEN_WEI_GUARD = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 10 },
    CLASS_UNIT_HERO_TKH_WU_SHENG_GUARD = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 20, EXTRA_DAMAGE_BOUNS = { 50, 1.3 } },
    CLASS_UNIT_HERO_TKH_YAN_YUN_GUARD = { EXTRA_ARMOR = 250, EXTRA_HEAL_TURNEND = 20, },
    CLASS_UNIT_HERO_TKH_TAN_LANG_GUARD = { EXTRA_ARMOR = 250, EXTRA_HEAL_TURNEND = 20, },
    CLASS_UNIT_HERO_TKH_CAO_SHI_GUARD = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 10, },
    CLASS_UNIT_HERO_TKH_MAN_ZU_GUARD = { EXTRA_ARMOR = 300, EXTRA_HEAL_TURNEND = 30, },
    CLASS_UNIT_HERO_TKH_HE_SHUO_GUARD = { EXTRA_ARMOR = 200, },
    CLASS_UNIT_HERO_TKH_BAI_ER_GUARD = { EXTRA_ARMOR = 200, EXTRA_CRIT_PERCENT = 20 },
    CLASS_UNIT_HERO_TKH_LIN_JIANG_GUARD = { EXTRA_ARMOR = 100, },
}


PROMOTED_EXTRA_ARMOR = {
    PROMOTION_TK_MU_LU_1_1 = 50,
    PROMOTION_TK_ZHU_RONG_1_4 = 50,
    PROMOTION_TK_SHA_MOKE_1_3 = 50,
    PROMOTION_TK_LV_LINGQI_1_2 = 50,
    PROMOTION_TK_LV_LINGQI_1_3 = 50,
    PROMOTION_TK_CAO_REN_1_3 = 50,
    PROMOTION_TK_CAO_REN_3_2 = 50,
    PROMOTION_TK_CAO_REN_3_3 = 50,
    PROMOTION_TK_YUAN_SHAO_1_4 = 50,
    PROMOTION_TK_SUN_QUAN_3_4 = 80,
    PROMOTION_TK_SUN_SHANGXIANG_1_1 = 30,
    PROMOTION_TK_SUN_SHANGXIANG_3_3 = 30,
    PROMOTION_TK_SUN_CE_1_1 = 30,
    PROMOTION_TK_TAISHI_CI_1_4 = 50,
    PROMOTION_TK_JIANG_WEI_1_3 = 50,
    -- 副将
    PROMOTION_TK_ZHAO_TONG_1_3 = 150,
    PROMOTION_TK_MA_YUN_LU_1_3 = 150,
    PROMOTION_TK_GUAN_YIN_PING_1_3 = 150,
    PROMOTION_TK_ZHANG_XING_CAI_1_3 = 200,
    PROMOTION_TK_GAO_SHUN_1_3 = 150,
    PROMOTION_TK_ZHANG_HE_1_3 = 150,
    PROMOTION_TK_XIA_HOU_DUN_1_3 = 150,
    PROMOTION_TK_PANG_DE_1_3 = 150,
    PROMOTION_TK_XU_HUANG_1_3 = 150,
    PROMOTION_TK_GAN_NING_1_3 = 150,
    PROMOTION_TK_WEI_YAN_1_3 = 200,
    PROMOTION_TK_JI_LING_1_3 = 200,
    PROMOTION_TK_SHI_BIAN_1_3 = 200,
    PROMOTION_TK_LIU_YAN_1_3 = 200,
    PROMOTION_TK_GONG_SUN_ZAN_1_3 = 150,
    PROMOTION_TK_WEN_PIN_1_3 = 150,
    PROMOTION_TK_WU_HUO_DONG_ZHU_1_3 = 150,
    PROMOTION_TK_CHE_LI_JI_1_3 = 150,
    PROMOTION_TK_BEI_MI_HU_1_3 = 150,
    PROMOTION_TK_HUA_XIONG_1_3 = 150,
    PROMOTION_TK_LI_JUE_1_3 = 150,
    PROMOTION_TK_GUO_SI_1_3 = 200,
}



ABILITIES_CRIT_PERCENT = {
    ABILITY_TKH_EQUIPMENT_SUIT_YUANYANG4 = 70,
    ABILITY_TKH_EQUIPMENT_SUIT_HUNTIAN4 = 40,
    ABILITY_TKH_EQUIPMENT_HunTianChui = 30,
    ABILITY_TKH_EQUIPMENT_SUIT_HANBING3 = 50,
    ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_UNIQUE_CAO_REN = 50,
    ABILITY_TKH_EQUIPMENT_FeiJiangZhanGong = 30,
    ABILITY_TKH_S_HERO_SKILL_PANG_DE_2 = 70,
    ABILITY_TKH_S_HERO_SKILL_XU_HUANG_3 = 30,
    ABILITY_TKH_S_HERO_SKILL_ZHANG_HE_7 = 10,
    ABILITY_MODIFIER_PROMOTION_TK_XIAHOU_YUAN_3_5 = 15,
    ABILITY_TKH_EQUIPMENT_SUIT_WUSHENG4 = 50,
}

ABILITIES_ARMOR = {
    ABILITY_TKH_EQUIPMENT_SUIT_JUXIANG3 = 150,
    ABILITY_TKH_EQUIPMENT_SUIT_TIEXIANG3 = 150,
    ABILITY_TKH_EQUIPMENT_SUIT_MANXUE3 = 150,
    ABILITY_TKH_EQUIPMENT_SUIT_SHUIMIAO3 = 150,
    ABILITY_TKH_EQUIPMENT_SUIT_LEIDIAN3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_YINXUE3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_SHANBI3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_HAOYUE3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_JISHEN3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_LIERI3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_FEIJIANG3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_HUNTIAN3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_WUWANG3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_YUANYANG3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_BAWANG3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_PILI3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_WEIWANG3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_HUNTIE3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_ZHONGPAO3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_WUZHUI3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_WUZHUI4 = 150,
    ABILITY_TKH_EQUIPMENT_SUIT_JINSHA3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_YINSHI3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_WUSHENG3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_HANWANG3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_LIANJI3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_QILIN3 = 100,
    ABILITY_TKH_EQUIPMENT_SUIT_LIEYAN4 = 150,
    ABILITY_TKH_EQUIPMENT_SUIT_HUNTIE4 = 150,
    ABILITY_TKH_EQUIPMENT_SUIT_HANWANG4 = 150,
    ABILITY_TKH_EQUIPMENT_SUIT_POJIA4 = 80
}

TURN_END_HEAL_PROMOTION = {
    PROMOTION_TK_ZHAO_TONG_3_2 = 10,
    PROMOTION_TK_MA_YUN_LU_3_2 = 10,
    PROMOTION_TK_GUAN_YIN_PING_3_2 = 10,
    PROMOTION_TK_ZHANG_XING_CAI_3_2 = 10,
    PROMOTION_TK_GAO_SHUN_3_2 = 10,
    PROMOTION_TK_ZHANG_HE_3_2 = 10,
    PROMOTION_TK_XIA_HOU_DUN_3_2 = 10,
    PROMOTION_TK_PANG_DE_3_2 = 10,
    PROMOTION_TK_XU_HUANG_3_2 = 10,
    PROMOTION_TK_GAN_NING_3_2 = 10,
    PROMOTION_TK_WEI_YAN_3_2 = 10,
    PROMOTION_TK_GONG_SUN_ZAN_3_2 = 10,
}

-- 单位每回合结束回复生命值
TURN_END_HEAL = {
    -- 英雄单位升级项
    ABILITY_MODIFIER_PROMOTION_TK_MU_LU_1_4 = 15,
    ABILITY_MODIFIER_PROMOTION_TK_MAN_XUE = 15,
    ABILITY_MODIFIER_PROMOTION_TK_LV_BU_3_5 = 15,
    ABILITY_MODIFIER_PROMOTION_TK_LIAO_XUE = 15,
    ABILITY_MODIFIER_PROMOTION_TK_DONG_ZHUO_3_5 = 30,
    ABILITY_MODIFIER_PROMOTION_TK_DIAN_WEI_1_5 = 30,
    ABILITY_MODIFIER_PROMOTION_TK_XIAHOU_YUAN_1_4 = 15,
    ABILITY_MODIFIER_PROMOTION_TK_WEN_CHOU_3_5 = 15,
    ABILITY_MODIFIER_PROMOTION_TK_MA_CHAO_3_5 = 15,
    ABILITY_MODIFIER_PROMOTION_TK_ZHAO_YUN_1_4 = 15,
    ABILITY_MODIFIER_PROMOTION_TK_GUAN_YU_3_5 = 15,
    ABILITY_MODIFIER_PROMOTION_TK_LIU_BEI_1_5 = 20,
    ABILITY_MOD_ABILITY_MODIFIER_PROMOTION_TK_SHI_BIAN_1_4 = 20,
    -- 装备
    ABILITY_TKH_EQUIPMENT_LongLinjia = 15,
    ABILITY_TKH_EQUIPMENT_QiLinJia = 25,
    ABILITY_TKH_EQUIPMENT_QiLinJu = 15,
    ABILITY_TKH_EQUIPMENT_TaiPingYaoShu = 20,
    ABILITY_TKH_EQUIPMENT_CaiTuan = 10,
    ABILITY_TKH_EQUIPMENT_SaLuZi = 20,
    ABILITY_TKH_EQUIPMENT_FangTianHuaJi_HeroExclusive = 10,
    ABILITY_TKH_EQUIPMENT_QingLongYanYueDao_HeroExclusive = 10,
    ABILITY_TKH_EQUIPMENT_PiLiFu_HeroExclusive = 10,
    ABILITY_TKH_EQUIPMENT_GuanShiFu_HeroExclusive = 10,
    ABILITY_TKH_EQUIPMENT_TuYao = 10,
    ABILITY_TKH_EQUIPMENT_LieYanShenJu_HeroExclusive = 10,
    ABILITY_TKH_EQUIPMENT_LiFeiSha = 10,
    ABILITY_TKH_EQUIPMENT_ManXueShenJu_HeroExclusive = 10,

    -- 套装
    ABILITY_TKH_EQUIPMENT_SUIT_LIEYAN3 = 20,
    ABILITY_TKH_EQUIPMENT_SUIT_PILI4 = 40,
    ABILITY_MODIFIER_ABILITY_TKH_EQUIPMENT_SUIT_QILIN4 = 20,
    -- 技能点
    ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_UNIQUE_MU_LU = 40,
    -- ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_UNIQUE_ZHAO_YUN = 10,
    ABILITY_TKH_HERO_UNIT_KILL_POINT_UPGRADE_UNIQUE_ZHAO_YUN_HEAL_ABILITY = 10,
    -- 羁绊
    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_YIMUTONGBAO_SUN_CE = 20,
    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_YIMUTONGBAO_SUN_QUAN = 20,
    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_NANMANRUQIN_MU_LU = 30,
    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_WUHUSHANGJIANG_GUAN_YU = 15,
    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_WUHUSHANGJIANG_ZHANG_FEI = 15,
    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_WUHUSHANGJIANG_ZHAO_YUN = 15,
    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_WUHUSHANGJIANG_MA_CHAO = 15,
    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_WUHUSHANGJIANG_HUANG_ZHONG = 15,

    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_NAN_MAN_RU_QIN_ZHU_RONG = 30,
    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_NAN_MAN_RU_QIN_MU_LU = 30,
    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_NAN_MAN_RU_QIN_WU_TUGU = 30,
    ABILITY_MODIFIER_ABILITY_RELATIONSHIP_YINGXIONGMEINV_LV_LINGQI = 20,

    -- 技能
    ABILITY_UNIT_HERO_TKH_GUO_JIA_AOE = 10,

    -- 大城市
    ABILITY_MODIFIER_GREAT_CITY_PROPERTY_GREAT_CITY_JIANNING_A = 20,
    ABILITY_MODIFIER_GREAT_CITY_PROPERTY_GREAT_CITY_CHANGSHA_A = 5,
    ABILITY_MODIFIER_GREAT_CITY_PROPERTY_GREAT_CITY_HANZHONG_A = 10,
    ABILITY_MODIFIER_GREAT_CITY_PROPERTY_GREAT_CITY_SHOUCHUN_B = 10,
    ABILITY_MODIFIER_GREAT_CITY_PROPERTY_GREAT_CITY_WUWEI_B = 10,
    ABILITY_MODIFIER_GREAT_CITY_PROPERTY_GREAT_CITY_JUYAN_A = 20,
    ABILITY_MODIFIER_GREAT_CITY_PROPERTY_GREAT_CITY_LIAODONG_A = 10,
    ABILITY_MODIFIER_GREAT_CITY_PROPERTY_GREAT_CITY_JIANG_A = 10,
    ABILITY_MODIFIER_GREAT_CITY_PROPERTY_GREAT_CITY_XUCHANG_A = 10,
    -- 其他
    ABILITY_TKH_EA_YILIAOBAO = 7,

}



-- =========================
-- GREAT PERSON
-- =========================

-- 大将军赋予能力，单位类型不匹配
AbilityBannedUnitType = {}
-- AbilityBannedUnitType.UNIT_HERO_TKH_MENG_HUO_GUARD = true
-- AbilityBannedUnitType.UNIT_HERO_TKH_ZHANG_LIAO_GUARD = true
-- AbilityBannedUnitType.UNIT_HERO_TKH_SUN_CE_GUARD = true

ExplosionDamage = 30
-- =========================
-- EQUIPMENT
-- =========================

EQUIPMENT_DATA_TYPE = {}
EQUIPMENT_DATA_TYPE.EQUIPMENT = 0
EQUIPMENT_DATA_TYPE.HERO_EQUIPMENT = 1

EQUIPMENT_REWARD_TYPES = {}
EQUIPMENT_REWARD_TYPES.TOTAL_KILL = 1
EQUIPMENT_REWARD_TYPES.DESTORY_BARBARIAN_CAMP = 2
EQUIPMENT_REWARD_TYPES.GOODYHUT_REWARD = 3
EQUIPMENT_REWARD_TYPES.CONQUERED_ORIGINAL_CAPITAL = 4
EQUIPMENT_REWARD_TYPES.TOTAL_CITIES = 5
EQUIPMENT_REWARD_TYPES.PROJECT_CREATED = 6
EQUIPMENT_REWARD_TYPES.HERO_TOTAL_KILL = 7
EQUIPMENT_REWARD_TYPES.WORLD_LORD = 8


EQUIPMENT_REWARD_REQUIREMENTS = {}
EQUIPMENT_REWARD_REQUIREMENTS[EQUIPMENT_REWARD_TYPES.TOTAL_CITIES] = {}
EQUIPMENT_REWARD_REQUIREMENTS[EQUIPMENT_REWARD_TYPES.DESTORY_BARBARIAN_CAMP] = { 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4 }
EQUIPMENT_REWARD_REQUIREMENTS[EQUIPMENT_REWARD_TYPES.GOODYHUT_REWARD] = {}

EQUIPMENT_REWARD_HERO_REQUIREMENTS = {
    -- 孟获、祝融夫人、木鹿大王、沙摩柯、朵思大王中的任何一人，木鹿大王获得：“巨象战鼓”。
    -- "MENG_HUO,ZHU_RONG,MU_LU,SHA_MOKE,DUO_SI",'EQUIPMENT_JuXiangZhanGu'
}


EquipmentConstants = {}
EquipmentConstants.SALUZI_RATE = 0.5
EquipmentConstants.LIE_YAN_ZHAN_CHUI_DAMAGE = 20
EquipmentConstants.QI_XING_DAO_RATE = 0.5
EquipmentConstants.HUN_TIAN_CHUI_RATE = 0.3
EquipmentConstants.LIANG_HAO_DAO_RATE = 0.4
EquipmentConstants.LIANG_HAO_DAO_RATE_SETTLER = 0.1
EquipmentConstants.WU_ZHANG_COOL = 3
EquipmentConstants.WU_ZHANG_DAMAGE = 30
EquipmentConstants.YIN_XUE_DAO_RATE = 0.05


ICON = "ICON_"
PORTRAIT = "_PORTRAIT"
PUT_ON = 1
TAKE_OFF = 0
RE_CREATE = -1

EQUIPMENT_STATUS = {}
EQUIPMENT_STATUS.SOLD = 1
EQUIPMENT_STATUS.BUY = 2
EQUIPMENT_STATUS.TAKE_OFF = 3
EQUIPMENT_STATUS.PUT_ON = 4
EQUIPMENT_STATUS.RE_PUT_ON = 5

TAKE_OFF_COST = 100
-- 装备出售价格
-- EQUIPMENT_SOLD_PRICE = 1000
EQUIPMENT_SOLD_PRICE = 2000
EQUIPMENT_BUY_PRICE = 6000

SHUFFL_TURN = 30
-- =========================
-- LUXURY
-- =========================

LUXURY_UNIT_NUM_MAX = 50
CAPITAL_MAX_UNIT_NUM = 10
PER_CITY_MAX_UNIT_NUM = 3

LUXURY_TAX_UNIT = { {
    UNITS_NUM = 0,
    TAX = 20
}, {
    UNITS_NUM = 5,
    TAX = 10
}, {
    UNITS_NUM = 11,
    TAX = 20
} }

LUXURY_TAX_CITY = { -- { CITIES_NUM = 1,  TAX = 200 },
    {
        CITIES_NUM = 10,
        TAX = 20
    }, {
    CITIES_NUM = 15,
    TAX = 30
}, {
    CITIES_NUM = 20,
    TAX = 50
} }

-- =========================
-- COMMAND
-- =========================
CommandBuildRouteConstants = {}
CommandBuildRouteConstants.ROUTE_LEVEL_1 = GameInfo.Routes['ROUTE_INDUSTRIAL_ROAD'].Index
CommandBuildRouteConstants.ROUTE_LEVEL_1_IRON_AMOUNT = 2
CommandBuildRouteConstants.ROUTE_LEVEL_1_GOLD_AMOUNT = 20
CommandBuildRouteConstants.ROUTE_LEVEL_2 = GameInfo.Routes['ROUTE_MODERN_ROAD'].Index
CommandBuildRouteConstants.ROUTE_LEVEL_2_IRON_AMOUNT = 5
CommandBuildRouteConstants.ROUTE_LEVEL_2_GOLD_AMOUNT = 50

CommandRecoverType = {}
CommandRecoverType.NEVER = 0
CommandRecoverType.PER_TURN = 1
CommandRecoverType.PER_ERA = 2
CommandRecoverType.PROPERTY = 3

CommandChangePlotType = {}
CommandChangePlotType.Features = 0
CommandChangePlotType.Terrains = 1
CommandChangePlotType.Improvements = 2


CHANGE_PLAYER_BALANCE_REASON = {}
CHANGE_PLAYER_BALANCE_REASON.TAKE_OFF_EQUIPMENT = 0
CHANGE_PLAYER_BALANCE_REASON.SELL_EQUIPMENT = 1
CHANGE_PLAYER_BALANCE_REASON.BUY_EQUIPMENT = 1


-- BOSS
HUANG_JING_ARMY = {}
HUANG_JING_ARMY.COUNT = 8


GREATPEOPLE_VALID_RESOURCES = {
    'RESOURCE_TEA',
    'RESOURCE_MARBLE',
    'RESOURCE_HONEY',
    'RESOURCE_CITRUS',
    'RESOURCE_OLIVES',
    'RESOURCE_TURTLES',
    'RESOURCE_AMBER',
    'RESOURCE_WHALES',
    'RESOURCE_COFFEE',
    'RESOURCE_COCOA',
    'RESOURCE_COTTON',
    'RESOURCE_FURS',
    'RESOURCE_WINE',
    'RESOURCE_GYPSUM',
    'RESOURCE_MERCURY',
    'RESOURCE_SILK',
    'RESOURCE_TRUFFLES',
    'RESOURCE_SUGAR',
    'RESOURCE_SPICES',
    'RESOURCE_IVORY',
    'RESOURCE_INCENSE',
    'RESOURCE_TOBACCO',
    'RESOURCE_SALT',
    'RESOURCE_SILVER',
    'RESOURCE_JADE',
    'RESOURCE_PEARLS',
    'RESOURCE_DIAMONDS',
    'RESOURCE_DYES',
    'RESOURCE_RICE',
    'RESOURCE_DEER',
    'RESOURCE_CATTLE',
    'RESOURCE_CRABS',
    'RESOURCE_STONE',
    'RESOURCE_COPPER',
    'RESOURCE_BANANAS',
    'RESOURCE_WHEAT',
    'RESOURCE_SHEEP',
    'RESOURCE_FISH',
    'RESOURCE_MAIZE'
}
