-- =========================
-- SYSTEM
-- =========================
TKH_ObjectType = {}
TKH_ObjectType.Game = -1
TKH_ObjectType.Player = 0
TKH_ObjectType.Unit = 1
TKH_ObjectType.City = 2
TKH_ObjectType.Plot = 3



TXT_CONFIRM_POPUP_YES = Locale.Lookup("LOC_CONFIRM_PROMPT_YES")
TXT_CONFIRM_POPUP_NO = Locale.Lookup("LOC_CONFIRM_PROMPT_NO")
DELETE_CITY_EXCHANGE = 1000



CombatVSComponentTypes = {}
CombatVSComponentTypes.UNIT_UNIT = 1
CombatVSComponentTypes.UNIT_CITY = 2
CombatVSComponentTypes.UNIT_DISTRICT = 4
CombatVSComponentTypes.CITY_UNIT = 8
CombatVSComponentTypes.DISTRICT_UNIT = 16

-- 单位击杀叠加最大攻击力
MELEES_UTNI_COMBAT_STRENGTH_BY_PER_KILL_MAX = 10
-- 特殊兵种击杀叠加最大攻击力
SPECIAL_UNIT_COMBAT_STRENGTH_BY_PER_KILL_MAX = 5

-- =========================
-- PROJECT
-- =========================
CREATE_EQUIPMENT_GOLD_AMOUNT = 1000
CREATE_EQUIPMENT_HORSES_AMOUNT = 120
CREATE_EQUIPMENT_IRON_AMOUNT = 120

-- CREATE_EQUIPMENT_GOLD_AMOUNT = 1
-- CREATE_EQUIPMENT_HORSES_AMOUNT = 1
-- CREATE_EQUIPMENT_IRON_AMOUNT = 1

PROJECT_CREATE_EQUIPMENT_MOUNT = 'PROJECT_CREATE_EQUIPMENT_MOUNT'
PROJECT_CREATE_EQUIPMENT_MOUNT_INDEX = GameInfo.Projects[PROJECT_CREATE_EQUIPMENT_MOUNT].Index
PROJECT_CREATE_EQUIPMENT_WEAPON = 'PROJECT_CREATE_EQUIPMENT_WEAPON'
PROJECT_CREATE_EQUIPMENT_WEAPON_INDEX = GameInfo.Projects[PROJECT_CREATE_EQUIPMENT_WEAPON].Index

-- =========================
-- CIVIC
-- =========================

CIVIC_FEUDALISM_INDEX = GameInfo.Civics['CIVIC_FEUDALISM'].Index

-- =========================
-- RESOURCE
-- =========================

RESOURCE_HORSES_INDEX = GameInfo.Resources['RESOURCE_HORSES'].Index
RESOURCE_IRON_INDEX = GameInfo.Resources['RESOURCE_IRON'].Index

GREAT_CITIES_RESOURCE = {}
GREAT_CITIES_RESOURCE['咸阳'] = { RESOURCE_IRON_INDEX, 4 }
GREAT_CITIES_RESOURCE['长安'] = { RESOURCE_IRON_INDEX, 4 }

GREAT_CITIES_RESOURCE['雒阳'] = { RESOURCE_IRON_INDEX, 4 }
GREAT_CITIES_RESOURCE['洛阳'] = { RESOURCE_IRON_INDEX, 4 }

GREAT_CITIES_RESOURCE['成都'] = { RESOURCE_IRON_INDEX, 4 }

GREAT_CITIES_RESOURCE['许'] = { RESOURCE_IRON_INDEX, 10 }
GREAT_CITIES_RESOURCE['许昌'] = { RESOURCE_IRON_INDEX, 10 }

GREAT_CITIES_RESOURCE['临淄'] = { RESOURCE_IRON_INDEX, 8 }
GREAT_CITIES_RESOURCE['邺城'] = { RESOURCE_IRON_INDEX, 8 }

GREAT_CITIES_RESOURCE['纪郢'] = { RESOURCE_HORSES_INDEX, 6 }
GREAT_CITIES_RESOURCE['江陵'] = { RESOURCE_HORSES_INDEX, 6 }

GREAT_CITIES_RESOURCE['单于庭'] = { RESOURCE_IRON_INDEX, 3 }

GREAT_CITIES_RESOURCE['绛'] = { RESOURCE_IRON_INDEX, 3 }
GREAT_CITIES_RESOURCE['晋阳'] = { RESOURCE_IRON_INDEX, 3 }

GREAT_CITIES_RESOURCE['蓟'] = { RESOURCE_IRON_INDEX, 3 }
GREAT_CITIES_RESOURCE['广阳'] = { RESOURCE_IRON_INDEX, 3 }
GREAT_CITIES_RESOURCE['北京'] = { RESOURCE_IRON_INDEX, 3 }

GREAT_CITIES_RESOURCE['会稽'] = { RESOURCE_IRON_INDEX, 3 }


GREAT_CITIES_ENCAMPMENT_COUNT = {}
GREAT_CITIES_ENCAMPMENT_COUNT['咸阳'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['长安'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['雒阳'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['洛阳'] = 4

GREAT_CITIES_ENCAMPMENT_COUNT['成都'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['许'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['许昌'] = 3

GREAT_CITIES_ENCAMPMENT_COUNT['徐'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['建业'] = 3

GREAT_CITIES_ENCAMPMENT_COUNT['临淄'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['邺城'] = 3

GREAT_CITIES_ENCAMPMENT_COUNT['纪郢'] = 3
GREAT_CITIES_ENCAMPMENT_COUNT['江陵'] = 3

GREAT_CITIES_ENCAMPMENT_COUNT['睢阳'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['单于庭'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['绛'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['晋阳'] = 2

GREAT_CITIES_ENCAMPMENT_COUNT['邯郸'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['雍'] = 4
GREAT_CITIES_ENCAMPMENT_COUNT['陈仓'] = 4

GREAT_CITIES_ENCAMPMENT_COUNT['蓟'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['广阳'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['北京'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['会稽'] = 2
GREAT_CITIES_ENCAMPMENT_COUNT['阖闾'] = 3

-- =========================
-- HERO
-- =========================

HeroConstants = {}

-- 赵云闪避几率
HeroConstants.ZHAO_YUN_DODGE_RATE = 0.5
HeroConstants.ZHOU_TAI_HEAL_RATE = 0.5
HeroConstants.ZHOU_TAI_YU_XUE_ATTACK = 3
-- 大将军文丑技能：造成伤害时吸血
HeroConstants.WEN_CHOU_RATE = 0.3
HeroConstants.WEN_CHOU_HEAL = 3
HeroConstants.SUN_SHANGXIANG_HEAL = 20
-- 周泰不屈恢复生命值/护甲值
HeroConstants.ZHOU_TAI_BUQU = 5
HeroConstants.HE_BEI_SHUANG_XIONG_HEAL = 15
HeroConstants.MULU_XIANGYU = 25
HeroConstants.ZHAOYUN_LONGWEI = 10
HeroConstants.GUAN_YU_RESTORE_MAX_TIMES = 2
-- 每次击杀获得的技能点
HeroConstants.SKILL_POINT_PER_KILL = 2

HeroConstants.ZHU_RONG_DAMAGE = 30
HeroConstants.SHA_MOKE_DAMAGE = 10

IMUTONGBAO_HEAL = 20
NANMANRUQIN_HEAL = 30
WUHUSHANGJIANG_HEAL = 15
CAOSHIHUWEI_CAO_CAO = GameInfo.UnitAbilities['ABILITY_MODIFIER_ABILITY_RELATIONSHIP_CAOSHIHUWEI_CAO_CAO'].Index
YIMUTONGBAO_SUN_QUAN = GameInfo.UnitAbilities['ABILITY_MODIFIER_ABILITY_RELATIONSHIP_YIMUTONGBAO_SUN_QUAN'].Index



-- =========================
-- UNIT
-- =========================
-- 34, 46, 58, 64, 76, 82, 90
UnitEraStrength = { 0, 16, 24, 30, 42, 48, 56, 62, 70 }

ADJACENT_UNIT =
{
    {
        ABILITY = 'ABILITY_TKH_EA_CHANGMAOZHEN',
        KEY = 'ADJACENT_CLASS_ANTI_CAVALRY',
        BOUNS = 4,
        TAGS = 'CLASS_ANTI_CAVALRY'
    },
    {
        ABILITY = 'ABILITY_TKH_EA_JIANDUNZHEN',
        KEY = 'ADJACENT_CLASS_MELEE',
        BOUNS = 3,
        TAGS = 'CLASS_MELEE'
    },
    {
        ABILITY = 'ABILITY_TKH_EA_JIANYUZHEN',
        KEY = 'ADJACENT_CLASS_RANGED',
        BOUNS = 2,
        TAGS = 'CLASS_RANGED'
    },
    {
        ABILITY = 'ABILITY_TKH_EA_QIBINGZHEN',
        KEY = 'ADJACENT_CLASS_CAVALRY',
        BOUNS = 3,
        TAGS = { 'CLASS_HEAVY_CAVALRY', 'CLASS_LIGHT_CAVALRY', 'CLASS_HEAVY_CHARIOT', 'CLASS_LIGHT_CHARIOT' }
    },
    {
        ABILITY = 'ABILITY_MOD_ABILITY_HERO_UNIT_KILL_POINT_UPGRADE_MANLI',
        KEY = 'ADJACENT_CLASS_UNIT_HERO_TKH_MENG_HUO_GUARD',
        BOUNS = 4,
        TAGS = { 'CLASS_UNIT_HERO_TKH_MENG_HUO_GUARD' }
    }
}

FULL_PROMOTED_REWARD_ABILITIES = {
    'ABILITY_TKH_FULL_PROMOTED_STRENGTH',
    'ABILITY_TKH_FULL_PROMOTED_DEFEND_STRENGTH',
    'ABILITY_TKH_FULL_PROMOTED_ATTACK_STRENGTH',
    'ABILITY_TKH_FULL_PROMOTED_MOVEMENT_1',
    'ABILITY_TKH_FULL_PROMOTED_MOVEMENT_2',
    'ABILITY_TKH_FULL_PROMOTED_EXTRA_ATTACK',
    'ABILITY_TKH_FULL_PROMOTED_BONUS_SIGHT',
    'ABILITY_TKH_FULL_PROMOTED_SILENT_RUNNING',
    'ABILITY_TKH_FULL_PROMOTED_DOUBLE_ENVELOPMENT',
}

NOT_FULL_PROMOTED_CLASS_TIMES = 5

NOT_FULL_PROMOTED_CLASS = {
    'CLASS_MELEE_TKH_UNIT',
    'CLASS_ANTI_CAVALRY_TKH_UNIT',
    'CLASS_LIGHT_CAVALRY_TKH_UNIT',
    'CLASS_HEAVY_CAVALRY_TKH_UNIT',
    'CLASS_RECON_TKH_UNIT',
    'CLASS_WARRIOR_MONK_TKH_UNIT',
    'CLASS_UNIT_HERO_TKH_MENG_HUO_GUARD',
    'CLASS_UNIT_HERO_TKH_ZHANG_LIAO_GUARD',
    'CLASS_UNIT_HERO_TKH_SUN_CE_GUARD',
    'CLASS_UNIT_HERO_TKH_LONG_WEI_GUARD',
    'CLASS_UNIT_HERO_TKH_SHEN_WEI_GUARD',
    'CLASS_UNIT_HERO_TKH_WU_SHENG_GUARD',
    'CLASS_UNIT_HERO_TKH_YAN_YUN_GUARD',
    'CLASS_UNIT_HERO_TKH_TAN_LANG_GUARD',
    'CLASS_UNIT_HERO_TKH_CAO_SHI_GUARD',
    'CLASS_UNIT_HERO_TKH_MAN_ZU_GUARD',
    -- 'CLASS_UNIT_HERO_TKH_HE_SHUO_GUARD',
    -- 'CLASS_UNIT_HERO_TKH_BAI_ER_GUARD',

}

FULL_PROMOTED_REWARD = {
    CLASS_MELEE_TKH_UNIT = { EXTRA_ARMOR = 300, EXTRA_HEAL_TURNEND = 30 },
    CLASS_RANGED_TKH_UNIT = { EXTRA_ARMOR = 100 },
    CLASS_ANTI_CAVALRY_TKH_UNIT = { EXTRA_ARMOR = 200, EXTRA_CRIT_PERCENT = 50 },
    CLASS_HEAVY_CAVALRY_TKH_UNIT = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 20 },
    CLASS_LIGHT_CAVALRY_TKH_UNIT = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 20 },
    CLASS_RECON_TKH_UNIT = { EXTRA_ARMOR = 200, EXTRA_CRIT_PERCENT = 50 },
    CLASS_SIEGE_TKH_UNIT = { EXTRA_ARMOR = 100 },
    CLASS_WARRIOR_MONK = { EXTRA_ARMOR = 200, EXTRA_DAMAGE_BOUNS = { 40, 1.5 } },

    CLASS_UNIT_HERO_TKH_MENG_HUO_GUARD = { EXTRA_ARMOR = 250, EXTRA_HEAL_TURNEND = 20 },
    CLASS_UNIT_HERO_TKH_ZHANG_LIAO_GUARD = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 10 },
    CLASS_UNIT_HERO_TKH_SUN_CE_GUARD = { EXTRA_ARMOR = 200, EXTRA_CRIT_PERCENT = 50 },

    CLASS_UNIT_HERO_TKH_LONG_WEI_GUARD = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 10, EXTRA_CRIT_PERCENT = 25 },
    CLASS_UNIT_HERO_TKH_SHEN_WEI_GUARD = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 10 },
    CLASS_UNIT_HERO_TKH_WU_SHENG_GUARD = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 20, EXTRA_DAMAGE_BOUNS = { 50, 1.3 } },
    CLASS_UNIT_HERO_TKH_YAN_YUN_GUARD = { EXTRA_ARMOR = 250, EXTRA_HEAL_TURNEND = 20, },
    CLASS_UNIT_HERO_TKH_TAN_LANG_GUARD = { EXTRA_ARMOR = 250, EXTRA_HEAL_TURNEND = 20, },
    CLASS_UNIT_HERO_TKH_CAO_SHI_GUARD = { EXTRA_ARMOR = 200, EXTRA_HEAL_TURNEND = 10, },
    CLASS_UNIT_HERO_TKH_MAN_ZU_GUARD = { EXTRA_ARMOR = 300, EXTRA_HEAL_TURNEND = 30, },
    CLASS_UNIT_HERO_TKH_HE_SHUO_GUARD = { EXTRA_ARMOR = 200, },
    CLASS_UNIT_HERO_TKH_BAI_ER_GUARD = { EXTRA_ARMOR = 200, EXTRA_CRIT_PERCENT = 20 },
    CLASS_UNIT_HERO_TKH_LIN_JIANG_GUARD = { EXTRA_ARMOR = 100, },


}


PROMOTED_EXTRA_ARMOR = {
    PROMOTION_TK_ARMOR_XIANG_JIA_MULU = 50
}


-- =========================
-- GREAT PERSON
-- =========================

-- 大将军赋予能力，单位类型不匹配
AbilityBannedUnitType = {}
-- AbilityBannedUnitType.UNIT_HERO_TKH_MENG_HUO_GUARD = true
-- AbilityBannedUnitType.UNIT_HERO_TKH_ZHANG_LIAO_GUARD = true
-- AbilityBannedUnitType.UNIT_HERO_TKH_SUN_CE_GUARD = true

ExplosionDamage = 30
-- =========================
-- EQUIPMENT
-- =========================

EQUIPMENT_DATA_TYPE = {}
EQUIPMENT_DATA_TYPE.EQUIPMENT = 0
EQUIPMENT_DATA_TYPE.HERO_EQUIPMENT = 1

EQUIPMENT_REWARD_TYPES = {}
EQUIPMENT_REWARD_TYPES.TOTAL_KILL = 1
EQUIPMENT_REWARD_TYPES.DESTORY_BARBARIAN_CAMP = 2
EQUIPMENT_REWARD_TYPES.GOODYHUT_REWARD = 3
EQUIPMENT_REWARD_TYPES.CONQUERED_ORIGINAL_CAPITAL = 4
EQUIPMENT_REWARD_TYPES.TOTAL_CITIES = 5
EQUIPMENT_REWARD_TYPES.PROJECT_CREATED = 6
EQUIPMENT_REWARD_TYPES.HERO_TOTAL_KILL = 7
EQUIPMENT_REWARD_TYPES.WORLD_LORD = 8


EQUIPMENT_REWARD_REQUIREMENTS = {}
-- EQUIPMENT_REWARD_REQUIREMENTS[EQUIPMENT_REWARD_TYPES.TOTAL_KILL] = {}
EQUIPMENT_REWARD_REQUIREMENTS[EQUIPMENT_REWARD_TYPES.TOTAL_CITIES] = {}
EQUIPMENT_REWARD_REQUIREMENTS[EQUIPMENT_REWARD_TYPES.DESTORY_BARBARIAN_CAMP] = { 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4 }
EQUIPMENT_REWARD_REQUIREMENTS[EQUIPMENT_REWARD_TYPES.GOODYHUT_REWARD] = {}

EquipmentConstants = {}
EquipmentConstants.SALUZI_RATE = 0.5
EquipmentConstants.LIE_YAN_ZHAN_CHUI_DAMAGE = 20
EquipmentConstants.QI_XING_DAO_RATE = 0.5
EquipmentConstants.HUN_TIAN_CHUI_RATE = 0.3
EquipmentConstants.LIANG_HAO_DAO_RATE = 0.4
EquipmentConstants.LIANG_HAO_DAO_RATE_SETTLER = 0.1
EquipmentConstants.WU_ZHANG_COOL = 3
EquipmentConstants.WU_ZHANG_DAMAGE = 30
EquipmentConstants.YIN_XUE_DAO_RATE = 0.05


ICON = "ICON_"
PORTRAIT = "_PORTRAIT"
PUT_ON = 1
TAKE_OFF = 0
RE_CREATE = -1

EQUIPMENT_STATUS = {}
EQUIPMENT_STATUS.SOLD = 1
EQUIPMENT_STATUS.BUY = 2
EQUIPMENT_STATUS.TAKE_OFF = 3
EQUIPMENT_STATUS.PUT_ON = 4
EQUIPMENT_STATUS.RE_PUT_ON = 5

TAKE_OFF_COST = 100
-- 装备出售价格
-- EQUIPMENT_SOLD_PRICE = 1000
EQUIPMENT_SOLD_PRICE = 2000
EQUIPMENT_BUY_PRICE = 6000

SHUFFL_TURN = 30
-- =========================
-- LUXURY
-- =========================

LUXURY_UNIT_NUM_MAX = 50
CAPITAL_MAX_UNIT_NUM = 10
PER_CITY_MAX_UNIT_NUM = 3

LUXURY_TAX_UNIT = { {
    UNITS_NUM = 0,
    TAX = 20
}, {
    UNITS_NUM = 5,
    TAX = 10
}, {
    UNITS_NUM = 11,
    TAX = 20
} }

LUXURY_TAX_CITY = { -- { CITIES_NUM = 1,  TAX = 200 },
    {
        CITIES_NUM = 10,
        TAX = 20
    }, {
    CITIES_NUM = 15,
    TAX = 30
}, {
    CITIES_NUM = 20,
    TAX = 50
} }

-- =========================
-- COMMAND
-- =========================
CommandBuildRouteConstants = {}
CommandBuildRouteConstants.ROUTE_LEVEL_1 = GameInfo.Routes['ROUTE_INDUSTRIAL_ROAD'].Index
CommandBuildRouteConstants.ROUTE_LEVEL_1_IRON_AMOUNT = 2
CommandBuildRouteConstants.ROUTE_LEVEL_1_GOLD_AMOUNT = 20
CommandBuildRouteConstants.ROUTE_LEVEL_2 = GameInfo.Routes['ROUTE_MODERN_ROAD'].Index
CommandBuildRouteConstants.ROUTE_LEVEL_2_IRON_AMOUNT = 5
CommandBuildRouteConstants.ROUTE_LEVEL_2_GOLD_AMOUNT = 50

CommandRecoverType = {}
CommandRecoverType.PER_TURN = 0
CommandRecoverType.PER_ERA = -1

CommandChangePlotType = {}
CommandChangePlotType.Features = 0
CommandChangePlotType.Terrains = 1
CommandChangePlotType.Improvements = 2


CHANGE_PLAYER_BALANCE_REASON = {}
CHANGE_PLAYER_BALANCE_REASON.TAKE_OFF_EQUIPMENT = 0
CHANGE_PLAYER_BALANCE_REASON.SELL_EQUIPMENT = 1
CHANGE_PLAYER_BALANCE_REASON.BUY_EQUIPMENT = 1


-- BOSS
HUANG_JING_ARMY = {}
HUANG_JING_ARMY.COUNT = 8


GREATPEOPLE_VALID_RESOURCES = {
    'RESOURCE_TEA',
    'RESOURCE_MARBLE',
    'RESOURCE_HONEY',
    'RESOURCE_CITRUS',
    'RESOURCE_OLIVES',
    'RESOURCE_TURTLES',
    'RESOURCE_AMBER',
    'RESOURCE_WHALES',
    'RESOURCE_COFFEE',
    'RESOURCE_COCOA',
    'RESOURCE_COTTON',
    'RESOURCE_FURS',
    'RESOURCE_WINE',
    'RESOURCE_GYPSUM',
    'RESOURCE_MERCURY',
    'RESOURCE_SILK',
    'RESOURCE_TRUFFLES',
    'RESOURCE_SUGAR',
    'RESOURCE_SPICES',
    'RESOURCE_IVORY',
    'RESOURCE_INCENSE',
    'RESOURCE_TOBACCO',
    'RESOURCE_SALT',
    'RESOURCE_SILVER',
    'RESOURCE_JADE',
    'RESOURCE_PEARLS',
    'RESOURCE_DIAMONDS',
    'RESOURCE_DYES',
    'RESOURCE_RICE',
    'RESOURCE_DEER',
    'RESOURCE_CATTLE',
    'RESOURCE_CRABS',
    'RESOURCE_STONE',
    'RESOURCE_COPPER',
    'RESOURCE_BANANAS',
    'RESOURCE_WHEAT',
    'RESOURCE_SHEEP',
    'RESOURCE_FISH',
    'RESOURCE_MAIZE'
}
